// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uurjmthjfupxtkxgsowa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1cmptdGhqZnVweHRreGdzb3dhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNDUwNzEsImV4cCI6MjA1OTcyMTA3MX0.s7QvIAEZ4l80HXThhujzdP_9Wfy1JJ6XHcQakvLEvEI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);
